; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__7B7A869E_ctype@h DB 01H
__457DD326_basetsd@h DB 01H
__4384A2D9_corecrt_memcpy_s@h DB 01H
__4E51A221_corecrt_wstring@h DB 01H
__2140C079_string@h DB 01H
__1887E595_winnt@h DB 01H
__9FC7C64B_processthreadsapi@h DB 01H
__FA470AEC_memoryapi@h DB 01H
__F37DAFF1_winerror@h DB 01H
__7A450CCC_winbase@h DB 01H
__B4B40122_winioctl@h DB 01H
__86261D59_stralign@h DB 01H
__630249ED_pmc_uint_debug@h DB 01H
__8245D7A3_test_op_remainder@c DB 01H
msvcjmc	ENDS
PUBLIC	TEST_PMC_Remainder_I_X
PUBLIC	TEST_PMC_Remainder_L_X
PUBLIC	TEST_PMC_Remainder_X_I
PUBLIC	TEST_PMC_Remainder_X_L
PUBLIC	TEST_PMC_Remainder_X_X
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@ ; `string'
PUBLIC	??_C@_1DE@HIGHFJBD@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@ ; `string'
PUBLIC	??_C@_1EK@BPKINACH@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@ ; `string'
PUBLIC	??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@ ; `string'
PUBLIC	??_C@_1DE@JAEEKCGL@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@ ; `string'
PUBLIC	??_C@_1EK@EEDGCDLJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@ ; `string'
PUBLIC	??_C@_1DE@DIINDGK@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ ; `string'
PUBLIC	??_C@_1EK@EDDDAGAA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ ; `string'
PUBLIC	??_C@_1DE@CIACADHF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ ; `string'
PUBLIC	??_C@_1EK@LHPJLJF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ ; `string'
PUBLIC	??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ ; `string'
PUBLIC	??_C@_1EK@PBDMOLIA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ ; `string'
PUBLIC	??_C@_1EG@MCOLJMDD@?$AAP?$AAM?$AAC?$AA_?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy@ ; `string'
EXTRN	TEST_Assert:PROC
EXTRN	FormatTestLabel:PROC
EXTRN	FormatTestMesssage:PROC
EXTRN	_RTC_CheckStackVars:PROC
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$TEST_PMC_Remainder_I_X DD imagerel $LN11
	DD	imagerel $LN11+491
	DD	imagerel $unwind$TEST_PMC_Remainder_I_X
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$TEST_PMC_Remainder_L_X DD imagerel $LN11
	DD	imagerel $LN11+494
	DD	imagerel $unwind$TEST_PMC_Remainder_L_X
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$TEST_PMC_Remainder_X_I DD imagerel $LN11
	DD	imagerel $LN11+491
	DD	imagerel $unwind$TEST_PMC_Remainder_X_I
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$TEST_PMC_Remainder_X_L DD imagerel $LN11
	DD	imagerel $LN11+494
	DD	imagerel $unwind$TEST_PMC_Remainder_X_L
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$TEST_PMC_Remainder_X_X DD imagerel $LN17
	DD	imagerel $LN17+910
	DD	imagerel $unwind$TEST_PMC_Remainder_X_X
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_EQUALS_MEMORY DD imagerel _EQUALS_MEMORY
	DD	imagerel _EQUALS_MEMORY+198
	DD	imagerel $unwind$_EQUALS_MEMORY
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_1EG@MCOLJMDD@?$AAP?$AAM?$AAC?$AA_?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy@
CONST	SEGMENT
??_C@_1EG@MCOLJMDD@?$AAP?$AAM?$AAC?$AA_?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'T', 00H, 'o', 00H, 'B', 00H
	DB	'y', 00H, 't', 00H, 'e', 00H, 'A', 00H, 'r', 00H, 'r', 00H, 'a'
	DB	00H, 'y', 00H, 'n0', 0a9H, '_0^', 0b3H, '0', 0fcH, '0', 0c9H, '0'
	DB	'L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH, '0g0o0j0D0(', 00H
	DB	'%', 00H, 'd', 00H, ')', 00H, 00H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_1EK@PBDMOLIA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
CONST	SEGMENT
??_C@_1EK@PBDMOLIA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'X', 00H, '_', 00H, 'X', 00H, 'n0', 0a9H, '_0^', 0b3H, '0'
	DB	0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH
	DB	'0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
CONST	SEGMENT
??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'X', 00H, '_', 00H, 'X', 00H, ' ', 00H, '(', 00H, '%', 00H
	DB	'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1EK@LHPJLJF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
CONST	SEGMENT
??_C@_1EK@LHPJLJF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'X', 00H, '_', 00H, 'L', 00H, 'n0', 0a9H, '_0^', 0b3H, '0'
	DB	0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH
	DB	'0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1DE@CIACADHF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
CONST	SEGMENT
??_C@_1DE@CIACADHF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'X', 00H, '_', 00H, 'L', 00H, ' ', 00H, '(', 00H, '%', 00H
	DB	'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1EK@EDDDAGAA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
CONST	SEGMENT
??_C@_1EK@EDDDAGAA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'X', 00H, '_', 00H, 'I', 00H, 'n0', 0a9H, '_0^', 0b3H, '0'
	DB	0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH
	DB	'0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1DE@DIINDGK@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
CONST	SEGMENT
??_C@_1DE@DIINDGK@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'X', 00H, '_', 00H, 'I', 00H, ' ', 00H, '(', 00H, '%', 00H
	DB	'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1EK@EEDGCDLJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@
CONST	SEGMENT
??_C@_1EK@EEDGCDLJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'L', 00H, '_', 00H, 'X', 00H, 'n0', 0a9H, '_0^', 0b3H, '0'
	DB	0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH
	DB	'0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1DE@JAEEKCGL@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@
CONST	SEGMENT
??_C@_1DE@JAEEKCGL@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'L', 00H, '_', 00H, 'X', 00H, ' ', 00H, '(', 00H, '%', 00H
	DB	'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
CONST	SEGMENT
??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@ DB 'p'
	DB	'RYOn0$PL0', 00H, 'N', 0f4H, 081H, 'W0j0D0', 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1EK@BPKINACH@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@
CONST	SEGMENT
??_C@_1EK@BPKINACH@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'I', 00H, '_', 00H, 'X', 00H, 'n0', 0a9H, '_0^', 0b3H, '0'
	DB	0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH
	DB	'0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1DE@HIGHFJBD@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@
CONST	SEGMENT
??_C@_1DE@HIGHFJBD@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'R', 00H, 'e', 00H, 'm', 00H
	DB	'a', 00H, 'i', 00H, 'n', 00H, 'd', 00H, 'e', 00H, 'r', 00H, '_'
	DB	00H, 'I', 00H, '_', 00H, 'X', 00H, ' ', 00H, '(', 00H, '%', 00H
	DB	'd', 00H, '.', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@
CONST	SEGMENT
??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@ DB 'P'
	DB	00H, 'M', 00H, 'C', 00H, '_', 00H, 'F', 00H, 'r', 00H, 'o', 00H
	DB	'm', 00H, 'B', 00H, 'y', 00H, 't', 00H, 'e', 00H, 'A', 00H, 'r'
	DB	00H, 'r', 00H, 'a', 00H, 'y', 00H, 'n0', 0a9H, '_0^', 0b3H, '0'
	DB	0fcH, '0', 0c9H, '0L0', 01fH, 'g', 085H, '_', 01aH, 090H, 08aH
	DB	'0g0o0j0D0(', 00H, '%', 00H, 'd', 00H, ')', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_EQUALS_MEMORY DD 025053901H
	DD	011d2322H
	DD	07016001dH
	DD	05015H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$TEST_PMC_Remainder_X_X DD 025054a19H
	DD	011d2322H
	DD	07016007bH
	DD	05015H
	DD	imagerel __GSHandlerCheck
	DD	03c0H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
TEST_PMC_Remainder_X_X$rtcName$0 DB 075H
	DB	00H
	ORG $+2
TEST_PMC_Remainder_X_X$rtcName$1 DB 076H
	DB	00H
	ORG $+2
TEST_PMC_Remainder_X_X$rtcName$2 DB 072H
	DB	00H
	ORG $+6
TEST_PMC_Remainder_X_X$rtcName$3 DB 061H
	DB	063H
	DB	074H
	DB	075H
	DB	061H
	DB	06cH
	DB	05fH
	DB	072H
	DB	05fH
	DB	062H
	DB	075H
	DB	066H
	DB	00H
	ORG $+3
TEST_PMC_Remainder_X_X$rtcName$4 DB 061H
	DB	063H
	DB	074H
	DB	075H
	DB	061H
	DB	06cH
	DB	05fH
	DB	072H
	DB	05fH
	DB	062H
	DB	075H
	DB	066H
	DB	05fH
	DB	073H
	DB	069H
	DB	07aH
	DB	065H
	DB	00H
	ORG $+14
TEST_PMC_Remainder_X_X$rtcVarDesc DD 01a8H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_X_X$rtcName$4
	DD	090H
	DD	0100H
	DQ	FLAT:TEST_PMC_Remainder_X_X$rtcName$3
	DD	068H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_X_X$rtcName$2
	DD	048H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_X_X$rtcName$1
	DD	028H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_X_X$rtcName$0
	ORG $+240
TEST_PMC_Remainder_X_X$rtcFrameData DD 05H
	DD	00H
	DQ	FLAT:TEST_PMC_Remainder_X_X$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$TEST_PMC_Remainder_X_L DD 025053901H
	DD	011d2322H
	DD	07016002dH
	DD	05015H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
TEST_PMC_Remainder_X_L$rtcName$0 DB 075H
	DB	00H
	ORG $+6
TEST_PMC_Remainder_X_L$rtcName$1 DB 061H
	DB	063H
	DB	074H
	DB	075H
	DB	061H
	DB	06cH
	DB	05fH
	DB	072H
	DB	00H
	ORG $+15
TEST_PMC_Remainder_X_L$rtcVarDesc DD 048H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_X_L$rtcName$1
	DD	028H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_X_L$rtcName$0
	ORG $+96
TEST_PMC_Remainder_X_L$rtcFrameData DD 02H
	DD	00H
	DQ	FLAT:TEST_PMC_Remainder_X_L$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$TEST_PMC_Remainder_X_I DD 025053901H
	DD	011d2322H
	DD	07016002dH
	DD	05015H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
TEST_PMC_Remainder_X_I$rtcName$0 DB 075H
	DB	00H
	ORG $+6
TEST_PMC_Remainder_X_I$rtcName$1 DB 061H
	DB	063H
	DB	074H
	DB	075H
	DB	061H
	DB	06cH
	DB	05fH
	DB	072H
	DB	00H
	ORG $+15
TEST_PMC_Remainder_X_I$rtcVarDesc DD 044H
	DD	04H
	DQ	FLAT:TEST_PMC_Remainder_X_I$rtcName$1
	DD	028H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_X_I$rtcName$0
	ORG $+96
TEST_PMC_Remainder_X_I$rtcFrameData DD 02H
	DD	00H
	DQ	FLAT:TEST_PMC_Remainder_X_I$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$TEST_PMC_Remainder_L_X DD 025053901H
	DD	011d2322H
	DD	07016002dH
	DD	05015H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
TEST_PMC_Remainder_L_X$rtcName$0 DB 076H
	DB	00H
	ORG $+6
TEST_PMC_Remainder_L_X$rtcName$1 DB 061H
	DB	063H
	DB	074H
	DB	075H
	DB	061H
	DB	06cH
	DB	05fH
	DB	072H
	DB	00H
	ORG $+15
TEST_PMC_Remainder_L_X$rtcVarDesc DD 048H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_L_X$rtcName$1
	DD	028H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_L_X$rtcName$0
	ORG $+96
TEST_PMC_Remainder_L_X$rtcFrameData DD 02H
	DD	00H
	DQ	FLAT:TEST_PMC_Remainder_L_X$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$TEST_PMC_Remainder_I_X DD 025053901H
	DD	011d2322H
	DD	07016002dH
	DD	05015H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
TEST_PMC_Remainder_I_X$rtcName$0 DB 076H
	DB	00H
	ORG $+6
TEST_PMC_Remainder_I_X$rtcName$1 DB 061H
	DB	063H
	DB	074H
	DB	075H
	DB	061H
	DB	06cH
	DB	05fH
	DB	072H
	DB	00H
	ORG $+15
TEST_PMC_Remainder_I_X$rtcVarDesc DD 044H
	DD	04H
	DQ	FLAT:TEST_PMC_Remainder_I_X$rtcName$1
	DD	028H
	DD	08H
	DQ	FLAT:TEST_PMC_Remainder_I_X$rtcName$0
	ORG $+96
TEST_PMC_Remainder_I_X$rtcFrameData DD 02H
	DD	00H
	DQ	FLAT:TEST_PMC_Remainder_I_X$rtcVarDesc
CONST	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_uint_debug.h
;	COMDAT _EQUALS_MEMORY
_TEXT	SEGMENT
buffer1$ = 224
count1$ = 232
buffer2$ = 240
count2$ = 248
_EQUALS_MEMORY PROC					; COMDAT

; 153  : {

	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 58					; 0000003aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+264]
	lea	rcx, OFFSET FLAT:__630249ED_pmc_uint_debug@h
	call	__CheckForDebuggerJustMyCode

; 154  :     if (count1 != count2)

	mov	rax, QWORD PTR count2$[rbp]
	cmp	QWORD PTR count1$[rbp], rax
	je	SHORT $LN4@EQUALS_MEM

; 155  :         return (-1);

	mov	eax, -1
	jmp	SHORT $LN1@EQUALS_MEM
$LN4@EQUALS_MEM:
$LN2@EQUALS_MEM:

; 156  :     while (count1 > 0)

	cmp	QWORD PTR count1$[rbp], 0
	jbe	SHORT $LN3@EQUALS_MEM

; 157  :     {
; 158  :         if (*buffer1 != *buffer2)

	mov	rax, QWORD PTR buffer1$[rbp]
	movzx	eax, BYTE PTR [rax]
	mov	rcx, QWORD PTR buffer2$[rbp]
	movzx	ecx, BYTE PTR [rcx]
	cmp	eax, ecx
	je	SHORT $LN5@EQUALS_MEM

; 159  :             return (-1);

	mov	eax, -1
	jmp	SHORT $LN1@EQUALS_MEM
$LN5@EQUALS_MEM:

; 160  :         ++buffer1;

	mov	rax, QWORD PTR buffer1$[rbp]
	inc	rax
	mov	QWORD PTR buffer1$[rbp], rax

; 161  :         ++buffer2;

	mov	rax, QWORD PTR buffer2$[rbp]
	inc	rax
	mov	QWORD PTR buffer2$[rbp], rax

; 162  :         --count1;

	mov	rax, QWORD PTR count1$[rbp]
	dec	rax
	mov	QWORD PTR count1$[rbp], rax

; 163  :     }

	jmp	SHORT $LN2@EQUALS_MEM
$LN3@EQUALS_MEM:

; 164  :     return (0);

	xor	eax, eax
$LN1@EQUALS_MEM:

; 165  : }

	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
_EQUALS_MEMORY ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\test_op_remainder.c
;	COMDAT TEST_PMC_Remainder_X_X
_TEXT	SEGMENT
u$ = 8
v$ = 40
r$ = 72
actual_r_buf$ = 112
actual_r_buf_size$ = 392
result$ = 420
u_result$ = 452
v_result$ = 484
r_result$ = 516
tv178 = 916
tv163 = 916
tv143 = 916
tv92 = 916
tv74 = 916
tv152 = 920
tv132 = 920
tv82 = 920
tv64 = 920
__$ArrayPad$ = 928
env$ = 976
ep$ = 984
no$ = 992
u_buf$ = 1000
u_buf_size$ = 1008
v_buf$ = 1016
v_buf_size$ = 1024
desired_return_code$ = 1032
desired_r_buf$ = 1040
desired_r_buf_size$ = 1048
TEST_PMC_Remainder_X_X PROC				; COMDAT

; 97   : {

$LN17:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 984				; 000003d8H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 246				; 000000f6H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+1016]
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rbp
	mov	QWORD PTR __$ArrayPad$[rbp], rax
	lea	rcx, OFFSET FLAT:__8245D7A3_test_op_remainder@c
	call	__CheckForDebuggerJustMyCode

; 98   :     PMC_HANDLE_UINT u;
; 99   :     PMC_HANDLE_UINT v;
; 100  :     PMC_HANDLE_UINT r;
; 101  :     unsigned char actual_r_buf[256];
; 102  :     size_t actual_r_buf_size;
; 103  :     PMC_STATUS_CODE result;
; 104  :     PMC_STATUS_CODE u_result;
; 105  :     PMC_STATUS_CODE v_result;
; 106  :     PMC_STATUS_CODE r_result;
; 107  :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_X (%d.%d)", no, 1), (u_result = ep->FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"PMC_FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	lea	r8, QWORD PTR u$[rbp]
	mov	rdx, QWORD PTR u_buf_size$[rbp]
	mov	rcx, QWORD PTR u_buf$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+48]
	mov	DWORD PTR u_result$[rbp], eax
	cmp	DWORD PTR u_result$[rbp], 0
	jne	SHORT $LN7@TEST_PMC_R
	mov	DWORD PTR tv74[rbp], 1
	jmp	SHORT $LN8@TEST_PMC_R
$LN7@TEST_PMC_R:
	mov	DWORD PTR tv74[rbp], 0
$LN8@TEST_PMC_R:
	mov	edx, DWORD PTR u_result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@
	call	FormatTestMesssage
	mov	QWORD PTR tv64[rbp], rax
	mov	r8d, 1
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv64[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv74[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 108  :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_X (%d.%d)", no, 2), (v_result = ep->FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"PMC_FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	lea	r8, QWORD PTR v$[rbp]
	mov	rdx, QWORD PTR v_buf_size$[rbp]
	mov	rcx, QWORD PTR v_buf$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+48]
	mov	DWORD PTR v_result$[rbp], eax
	cmp	DWORD PTR v_result$[rbp], 0
	jne	SHORT $LN9@TEST_PMC_R
	mov	DWORD PTR tv92[rbp], 1
	jmp	SHORT $LN10@TEST_PMC_R
$LN9@TEST_PMC_R:
	mov	DWORD PTR tv92[rbp], 0
$LN10@TEST_PMC_R:
	mov	edx, DWORD PTR v_result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@
	call	FormatTestMesssage
	mov	QWORD PTR tv82[rbp], rax
	mov	r8d, 2
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv82[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv92[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 109  :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_X (%d.%d)", no, 3), (r_result = ep->DivRem_X_X(u, v, NULL, &r)) == desired_return_code, FormatTestMesssage(L"PMC_Remainder_X_Xの復帰コードが期待通りではない(%d)", r_result));

	lea	r9, QWORD PTR r$[rbp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR v$[rbp]
	mov	rcx, QWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+256]
	mov	DWORD PTR r_result$[rbp], eax
	mov	eax, DWORD PTR desired_return_code$[rbp]
	cmp	DWORD PTR r_result$[rbp], eax
	jne	SHORT $LN11@TEST_PMC_R
	mov	DWORD PTR tv143[rbp], 1
	jmp	SHORT $LN12@TEST_PMC_R
$LN11@TEST_PMC_R:
	mov	DWORD PTR tv143[rbp], 0
$LN12@TEST_PMC_R:
	mov	edx, DWORD PTR r_result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@PBDMOLIA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestMesssage
	mov	QWORD PTR tv132[rbp], rax
	mov	r8d, 3
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv132[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv143[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 110  :     if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR desired_return_code$[rbp], 0
	jne	$LN2@TEST_PMC_R

; 111  :     {
; 112  :         TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_X (%d.%d)", no, 4), (result = ep->ToByteArray(r, actual_r_buf, sizeof(actual_r_buf), &actual_r_buf_size)) == PMC_STATUS_OK, FormatTestMesssage(L"PMC_ToByteArrayの復帰コードが期待通りではない(%d)", result));

	lea	r9, QWORD PTR actual_r_buf_size$[rbp]
	mov	r8d, 256				; 00000100H
	lea	rdx, QWORD PTR actual_r_buf$[rbp]
	mov	rcx, QWORD PTR r$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+56]
	mov	DWORD PTR result$[rbp], eax
	cmp	DWORD PTR result$[rbp], 0
	jne	SHORT $LN13@TEST_PMC_R
	mov	DWORD PTR tv163[rbp], 1
	jmp	SHORT $LN14@TEST_PMC_R
$LN13@TEST_PMC_R:
	mov	DWORD PTR tv163[rbp], 0
$LN14@TEST_PMC_R:
	mov	edx, DWORD PTR result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EG@MCOLJMDD@?$AAP?$AAM?$AAC?$AA_?$AAT?$AAo?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr?$AAa?$AAy@
	call	FormatTestMesssage
	mov	QWORD PTR tv152[rbp], rax
	mov	r8d, 4
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv152[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv163[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 113  :         TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_X (%d.%d)", no, 5), _EQUALS_MEMORY(actual_r_buf, actual_r_buf_size, desired_r_buf, desired_r_buf_size) == 0, L"剰余の値が一致しない");

	mov	r9, QWORD PTR desired_r_buf_size$[rbp]
	mov	r8, QWORD PTR desired_r_buf$[rbp]
	mov	rdx, QWORD PTR actual_r_buf_size$[rbp]
	lea	rcx, QWORD PTR actual_r_buf$[rbp]
	call	_EQUALS_MEMORY
	test	eax, eax
	jne	SHORT $LN15@TEST_PMC_R
	mov	DWORD PTR tv178[rbp], 1
	jmp	SHORT $LN16@TEST_PMC_R
$LN15@TEST_PMC_R:
	mov	DWORD PTR tv178[rbp], 0
$LN16@TEST_PMC_R:
	mov	r8d, 5
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@IGCJEDAJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	lea	r9, OFFSET FLAT:??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	r8d, DWORD PTR tv178[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert
$LN2@TEST_PMC_R:

; 114  :     }
; 115  :     if (r_result == PMC_STATUS_OK)

	cmp	DWORD PTR r_result$[rbp], 0
	jne	SHORT $LN3@TEST_PMC_R

; 116  :     {
; 117  :         ep->Dispose(r);

	mov	rcx, QWORD PTR r$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+32]
$LN3@TEST_PMC_R:

; 118  :     }
; 119  :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR v_result$[rbp], 0
	jne	SHORT $LN4@TEST_PMC_R

; 120  :         ep->Dispose(v);

	mov	rcx, QWORD PTR v$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+32]
$LN4@TEST_PMC_R:

; 121  :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR u_result$[rbp], 0
	jne	SHORT $LN5@TEST_PMC_R

; 122  :         ep->Dispose(u);

	mov	rcx, QWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+32]
$LN5@TEST_PMC_R:

; 123  : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:TEST_PMC_Remainder_X_X$rtcFrameData
	call	_RTC_CheckStackVars
	mov	rcx, QWORD PTR __$ArrayPad$[rbp]
	xor	rcx, rbp
	call	__security_check_cookie
	lea	rsp, QWORD PTR [rbp+952]
	pop	rdi
	pop	rbp
	ret	0
TEST_PMC_Remainder_X_X ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\test_op_remainder.c
;	COMDAT TEST_PMC_Remainder_X_L
_TEXT	SEGMENT
u$ = 8
actual_r$ = 40
result$ = 68
u_result$ = 100
tv136 = 308
tv93 = 308
tv74 = 308
tv82 = 312
tv64 = 312
env$ = 352
ep$ = 360
no$ = 368
u_buf$ = 376
u_buf_size$ = 384
v$ = 392
desired_return_code$ = 400
desired_r$ = 408
TEST_PMC_Remainder_X_L PROC				; COMDAT

; 81   : {

$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 360				; 00000168H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 90					; 0000005aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+392]
	lea	rcx, OFFSET FLAT:__8245D7A3_test_op_remainder@c
	call	__CheckForDebuggerJustMyCode

; 82   :     PMC_HANDLE_UINT u;
; 83   :     unsigned __int64 actual_r;
; 84   :     PMC_STATUS_CODE result;
; 85   :     PMC_STATUS_CODE u_result;
; 86   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_L (%d.%d)", no, 1), (u_result = ep->FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"PMC_FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	lea	r8, QWORD PTR u$[rbp]
	mov	rdx, QWORD PTR u_buf_size$[rbp]
	mov	rcx, QWORD PTR u_buf$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+48]
	mov	DWORD PTR u_result$[rbp], eax
	cmp	DWORD PTR u_result$[rbp], 0
	jne	SHORT $LN5@TEST_PMC_R
	mov	DWORD PTR tv74[rbp], 1
	jmp	SHORT $LN6@TEST_PMC_R
$LN5@TEST_PMC_R:
	mov	DWORD PTR tv74[rbp], 0
$LN6@TEST_PMC_R:
	mov	edx, DWORD PTR u_result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@
	call	FormatTestMesssage
	mov	QWORD PTR tv64[rbp], rax
	mov	r8d, 1
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@CIACADHF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv64[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv74[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 87   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_L (%d.%d)", no, 2), (result = ep->DivRem_X_L(u, v, NULL, &actual_r)) == desired_return_code, FormatTestMesssage(L"PMC_Remainder_X_Lの復帰コードが期待通りではない(%d)", result));

	lea	r9, QWORD PTR actual_r$[rbp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR v$[rbp]
	mov	rcx, QWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+248]
	mov	DWORD PTR result$[rbp], eax
	mov	eax, DWORD PTR desired_return_code$[rbp]
	cmp	DWORD PTR result$[rbp], eax
	jne	SHORT $LN7@TEST_PMC_R
	mov	DWORD PTR tv93[rbp], 1
	jmp	SHORT $LN8@TEST_PMC_R
$LN7@TEST_PMC_R:
	mov	DWORD PTR tv93[rbp], 0
$LN8@TEST_PMC_R:
	mov	edx, DWORD PTR result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@LHPJLJF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestMesssage
	mov	QWORD PTR tv82[rbp], rax
	mov	r8d, 2
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@CIACADHF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv82[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv93[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 88   :     if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR desired_return_code$[rbp], 0
	jne	SHORT $LN2@TEST_PMC_R

; 89   :     {
; 90   :         TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_L (%d.%d)", no, 3), actual_r == desired_r, L"剰余の値が一致しない");

	mov	rax, QWORD PTR desired_r$[rbp]
	cmp	QWORD PTR actual_r$[rbp], rax
	jne	SHORT $LN9@TEST_PMC_R
	mov	DWORD PTR tv136[rbp], 1
	jmp	SHORT $LN10@TEST_PMC_R
$LN9@TEST_PMC_R:
	mov	DWORD PTR tv136[rbp], 0
$LN10@TEST_PMC_R:
	mov	r8d, 3
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@CIACADHF@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	lea	r9, OFFSET FLAT:??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	r8d, DWORD PTR tv136[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert
$LN2@TEST_PMC_R:

; 91   :     }
; 92   :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR u_result$[rbp], 0
	jne	SHORT $LN3@TEST_PMC_R

; 93   :         ep->Dispose(u);

	mov	rcx, QWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+32]
$LN3@TEST_PMC_R:

; 94   : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:TEST_PMC_Remainder_X_L$rtcFrameData
	call	_RTC_CheckStackVars
	lea	rsp, QWORD PTR [rbp+328]
	pop	rdi
	pop	rbp
	ret	0
TEST_PMC_Remainder_X_L ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\test_op_remainder.c
;	COMDAT TEST_PMC_Remainder_X_I
_TEXT	SEGMENT
u$ = 8
actual_r$ = 36
result$ = 68
u_result$ = 100
tv136 = 308
tv93 = 308
tv74 = 308
tv82 = 312
tv64 = 312
env$ = 352
ep$ = 360
no$ = 368
u_buf$ = 376
u_buf_size$ = 384
v$ = 392
desired_return_code$ = 400
desired_r$ = 408
TEST_PMC_Remainder_X_I PROC				; COMDAT

; 65   : {

$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 360				; 00000168H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 90					; 0000005aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+392]
	lea	rcx, OFFSET FLAT:__8245D7A3_test_op_remainder@c
	call	__CheckForDebuggerJustMyCode

; 66   :     PMC_HANDLE_UINT u;
; 67   :     unsigned __int32 actual_r;
; 68   :     PMC_STATUS_CODE result;
; 69   :     PMC_STATUS_CODE u_result;
; 70   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_I (%d.%d)", no, 1), (u_result = ep->FromByteArray(u_buf, u_buf_size, &u)) == PMC_STATUS_OK, FormatTestMesssage(L"PMC_FromByteArrayの復帰コードが期待通りではない(%d)", u_result));

	lea	r8, QWORD PTR u$[rbp]
	mov	rdx, QWORD PTR u_buf_size$[rbp]
	mov	rcx, QWORD PTR u_buf$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+48]
	mov	DWORD PTR u_result$[rbp], eax
	cmp	DWORD PTR u_result$[rbp], 0
	jne	SHORT $LN5@TEST_PMC_R
	mov	DWORD PTR tv74[rbp], 1
	jmp	SHORT $LN6@TEST_PMC_R
$LN5@TEST_PMC_R:
	mov	DWORD PTR tv74[rbp], 0
$LN6@TEST_PMC_R:
	mov	edx, DWORD PTR u_result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@
	call	FormatTestMesssage
	mov	QWORD PTR tv64[rbp], rax
	mov	r8d, 1
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@DIINDGK@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv64[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv74[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 71   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_I (%d.%d)", no, 2), (result = ep->DivRem_X_I(u, v, NULL, &actual_r)) == desired_return_code, FormatTestMesssage(L"PMC_Remainder_X_Iの復帰コードが期待通りではない(%d)", result));

	lea	r9, QWORD PTR actual_r$[rbp]
	xor	r8d, r8d
	mov	edx, DWORD PTR v$[rbp]
	mov	rcx, QWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+240]
	mov	DWORD PTR result$[rbp], eax
	mov	eax, DWORD PTR desired_return_code$[rbp]
	cmp	DWORD PTR result$[rbp], eax
	jne	SHORT $LN7@TEST_PMC_R
	mov	DWORD PTR tv93[rbp], 1
	jmp	SHORT $LN8@TEST_PMC_R
$LN7@TEST_PMC_R:
	mov	DWORD PTR tv93[rbp], 0
$LN8@TEST_PMC_R:
	mov	edx, DWORD PTR result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@EDDDAGAA@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestMesssage
	mov	QWORD PTR tv82[rbp], rax
	mov	r8d, 2
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@DIINDGK@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv82[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv93[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 72   :     if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR desired_return_code$[rbp], 0
	jne	SHORT $LN2@TEST_PMC_R

; 73   :     {
; 74   :         TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_X_I (%d.%d)", no, 3), actual_r == desired_r, L"剰余の値が一致しない");

	mov	eax, DWORD PTR desired_r$[rbp]
	cmp	DWORD PTR actual_r$[rbp], eax
	jne	SHORT $LN9@TEST_PMC_R
	mov	DWORD PTR tv136[rbp], 1
	jmp	SHORT $LN10@TEST_PMC_R
$LN9@TEST_PMC_R:
	mov	DWORD PTR tv136[rbp], 0
$LN10@TEST_PMC_R:
	mov	r8d, 3
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@DIINDGK@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAX@
	call	FormatTestLabel
	lea	r9, OFFSET FLAT:??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	r8d, DWORD PTR tv136[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert
$LN2@TEST_PMC_R:

; 75   :     }
; 76   :     if (u_result == PMC_STATUS_OK)

	cmp	DWORD PTR u_result$[rbp], 0
	jne	SHORT $LN3@TEST_PMC_R

; 77   :         ep->Dispose(u);

	mov	rcx, QWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+32]
$LN3@TEST_PMC_R:

; 78   : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:TEST_PMC_Remainder_X_I$rtcFrameData
	call	_RTC_CheckStackVars
	lea	rsp, QWORD PTR [rbp+328]
	pop	rdi
	pop	rbp
	ret	0
TEST_PMC_Remainder_X_I ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\test_op_remainder.c
;	COMDAT TEST_PMC_Remainder_L_X
_TEXT	SEGMENT
v$ = 8
actual_r$ = 40
result$ = 68
v_result$ = 100
tv136 = 308
tv93 = 308
tv74 = 308
tv82 = 312
tv64 = 312
env$ = 352
ep$ = 360
no$ = 368
u$ = 376
v_buf$ = 384
v_buf_size$ = 392
desired_return_code$ = 400
desired_r$ = 408
TEST_PMC_Remainder_L_X PROC				; COMDAT

; 49   : {

$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 360				; 00000168H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 90					; 0000005aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+392]
	lea	rcx, OFFSET FLAT:__8245D7A3_test_op_remainder@c
	call	__CheckForDebuggerJustMyCode

; 50   :     PMC_HANDLE_UINT v;
; 51   :     unsigned __int64 actual_r;
; 52   :     PMC_STATUS_CODE result;
; 53   :     PMC_STATUS_CODE v_result;
; 54   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_L_X (%d.%d)", no, 1), (v_result = ep->FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"PMC_FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	lea	r8, QWORD PTR v$[rbp]
	mov	rdx, QWORD PTR v_buf_size$[rbp]
	mov	rcx, QWORD PTR v_buf$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+48]
	mov	DWORD PTR v_result$[rbp], eax
	cmp	DWORD PTR v_result$[rbp], 0
	jne	SHORT $LN5@TEST_PMC_R
	mov	DWORD PTR tv74[rbp], 1
	jmp	SHORT $LN6@TEST_PMC_R
$LN5@TEST_PMC_R:
	mov	DWORD PTR tv74[rbp], 0
$LN6@TEST_PMC_R:
	mov	edx, DWORD PTR v_result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@
	call	FormatTestMesssage
	mov	QWORD PTR tv64[rbp], rax
	mov	r8d, 1
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@JAEEKCGL@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv64[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv74[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 55   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_L_X (%d.%d)", no, 2), (result = ep->DivRem_L_X(u, v, NULL, &actual_r)) == desired_return_code, FormatTestMesssage(L"PMC_Remainder_L_Xの復帰コードが期待通りではない(%d)", result));

	lea	r9, QWORD PTR actual_r$[rbp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR v$[rbp]
	mov	rcx, QWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+232]
	mov	DWORD PTR result$[rbp], eax
	mov	eax, DWORD PTR desired_return_code$[rbp]
	cmp	DWORD PTR result$[rbp], eax
	jne	SHORT $LN7@TEST_PMC_R
	mov	DWORD PTR tv93[rbp], 1
	jmp	SHORT $LN8@TEST_PMC_R
$LN7@TEST_PMC_R:
	mov	DWORD PTR tv93[rbp], 0
$LN8@TEST_PMC_R:
	mov	edx, DWORD PTR result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@EEDGCDLJ@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@
	call	FormatTestMesssage
	mov	QWORD PTR tv82[rbp], rax
	mov	r8d, 2
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@JAEEKCGL@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv82[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv93[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 56   :     if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR desired_return_code$[rbp], 0
	jne	SHORT $LN2@TEST_PMC_R

; 57   :     {
; 58   :         TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_L_X (%d.%d)", no, 3), actual_r == desired_r, L"剰余の値が一致しない");

	mov	rax, QWORD PTR desired_r$[rbp]
	cmp	QWORD PTR actual_r$[rbp], rax
	jne	SHORT $LN9@TEST_PMC_R
	mov	DWORD PTR tv136[rbp], 1
	jmp	SHORT $LN10@TEST_PMC_R
$LN9@TEST_PMC_R:
	mov	DWORD PTR tv136[rbp], 0
$LN10@TEST_PMC_R:
	mov	r8d, 3
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@JAEEKCGL@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAL@
	call	FormatTestLabel
	lea	r9, OFFSET FLAT:??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	r8d, DWORD PTR tv136[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert
$LN2@TEST_PMC_R:

; 59   :     }
; 60   :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR v_result$[rbp], 0
	jne	SHORT $LN3@TEST_PMC_R

; 61   :         ep->Dispose(v);

	mov	rcx, QWORD PTR v$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+32]
$LN3@TEST_PMC_R:

; 62   : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:TEST_PMC_Remainder_L_X$rtcFrameData
	call	_RTC_CheckStackVars
	lea	rsp, QWORD PTR [rbp+328]
	pop	rdi
	pop	rbp
	ret	0
TEST_PMC_Remainder_L_X ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\test_op_remainder.c
;	COMDAT TEST_PMC_Remainder_I_X
_TEXT	SEGMENT
v$ = 8
actual_r$ = 36
result$ = 68
v_result$ = 100
tv136 = 308
tv93 = 308
tv74 = 308
tv82 = 312
tv64 = 312
env$ = 352
ep$ = 360
no$ = 368
u$ = 376
v_buf$ = 384
v_buf_size$ = 392
desired_return_code$ = 400
desired_r$ = 408
TEST_PMC_Remainder_I_X PROC				; COMDAT

; 33   : {

$LN11:
	mov	DWORD PTR [rsp+32], r9d
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 360				; 00000168H
	lea	rbp, QWORD PTR [rsp+32]
	mov	rdi, rsp
	mov	ecx, 90					; 0000005aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rcx, QWORD PTR [rsp+392]
	lea	rcx, OFFSET FLAT:__8245D7A3_test_op_remainder@c
	call	__CheckForDebuggerJustMyCode

; 34   :     PMC_HANDLE_UINT v;
; 35   :     unsigned __int32 actual_r;
; 36   :     PMC_STATUS_CODE result;
; 37   :     PMC_STATUS_CODE v_result;
; 38   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_I_X (%d.%d)", no, 1), (v_result = ep->FromByteArray(v_buf, v_buf_size, &v)) == PMC_STATUS_OK, FormatTestMesssage(L"PMC_FromByteArrayの復帰コードが期待通りではない(%d)", v_result));

	lea	r8, QWORD PTR v$[rbp]
	mov	rdx, QWORD PTR v_buf_size$[rbp]
	mov	rcx, QWORD PTR v_buf$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+48]
	mov	DWORD PTR v_result$[rbp], eax
	cmp	DWORD PTR v_result$[rbp], 0
	jne	SHORT $LN5@TEST_PMC_R
	mov	DWORD PTR tv74[rbp], 1
	jmp	SHORT $LN6@TEST_PMC_R
$LN5@TEST_PMC_R:
	mov	DWORD PTR tv74[rbp], 0
$LN6@TEST_PMC_R:
	mov	edx, DWORD PTR v_result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@HDEICNAJ@?$AAP?$AAM?$AAC?$AA_?$AAF?$AAr?$AAo?$AAm?$AAB?$AAy?$AAt?$AAe?$AAA?$AAr?$AAr@
	call	FormatTestMesssage
	mov	QWORD PTR tv64[rbp], rax
	mov	r8d, 1
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@HIGHFJBD@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv64[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv74[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 39   :     TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_I_X (%d.%d)", no, 2), (result = ep->DivRem_I_X(u, v, NULL, &actual_r)) == desired_return_code, FormatTestMesssage(L"PMC_Remainder_I_Xの復帰コードが期待通りではない(%d)", result));

	lea	r9, QWORD PTR actual_r$[rbp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR v$[rbp]
	mov	ecx, DWORD PTR u$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+224]
	mov	DWORD PTR result$[rbp], eax
	mov	eax, DWORD PTR desired_return_code$[rbp]
	cmp	DWORD PTR result$[rbp], eax
	jne	SHORT $LN7@TEST_PMC_R
	mov	DWORD PTR tv93[rbp], 1
	jmp	SHORT $LN8@TEST_PMC_R
$LN7@TEST_PMC_R:
	mov	DWORD PTR tv93[rbp], 0
$LN8@TEST_PMC_R:
	mov	edx, DWORD PTR result$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1EK@BPKINACH@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@
	call	FormatTestMesssage
	mov	QWORD PTR tv82[rbp], rax
	mov	r8d, 2
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@HIGHFJBD@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@
	call	FormatTestLabel
	mov	rcx, QWORD PTR tv82[rbp]
	mov	r9, rcx
	mov	r8d, DWORD PTR tv93[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert

; 40   :     if (desired_return_code == PMC_STATUS_OK)

	cmp	DWORD PTR desired_return_code$[rbp], 0
	jne	SHORT $LN2@TEST_PMC_R

; 41   :     {
; 42   :         TEST_Assert(env, FormatTestLabel(L"PMC_Remainder_I_X (%d.%d)", no, 3), actual_r == desired_r, L"剰余の値が一致しない");

	mov	eax, DWORD PTR desired_r$[rbp]
	cmp	DWORD PTR actual_r$[rbp], eax
	jne	SHORT $LN9@TEST_PMC_R
	mov	DWORD PTR tv136[rbp], 1
	jmp	SHORT $LN10@TEST_PMC_R
$LN9@TEST_PMC_R:
	mov	DWORD PTR tv136[rbp], 0
$LN10@TEST_PMC_R:
	mov	r8d, 3
	mov	edx, DWORD PTR no$[rbp]
	lea	rcx, OFFSET FLAT:??_C@_1DE@HIGHFJBD@?$AAP?$AAM?$AAC?$AA_?$AAR?$AAe?$AAm?$AAa?$AAi?$AAn?$AAd?$AAe?$AAr?$AA_?$AAI@
	call	FormatTestLabel
	lea	r9, OFFSET FLAT:??_C@_1BG@BPGLFLF@?$AAp?$AAY?$AAn?$AA$?$AAL?$AA?$AA?$PP?t?$AAW?$AAj?$AAD@
	mov	r8d, DWORD PTR tv136[rbp]
	mov	rdx, rax
	mov	rcx, QWORD PTR env$[rbp]
	call	TEST_Assert
$LN2@TEST_PMC_R:

; 43   :     }
; 44   :     if (v_result == PMC_STATUS_OK)

	cmp	DWORD PTR v_result$[rbp], 0
	jne	SHORT $LN3@TEST_PMC_R

; 45   :         ep->Dispose(v);

	mov	rcx, QWORD PTR v$[rbp]
	mov	rax, QWORD PTR ep$[rbp]
	call	QWORD PTR [rax+32]
$LN3@TEST_PMC_R:

; 46   : }

	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:TEST_PMC_Remainder_I_X$rtcFrameData
	call	_RTC_CheckStackVars
	lea	rsp, QWORD PTR [rbp+328]
	pop	rdi
	pop	rbp
	ret	0
TEST_PMC_Remainder_I_X ENDP
_TEXT	ENDS
END
