; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27026.1 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	From_I_Imp
PUBLIC	From_L_Imp
PUBLIC	Initialize_From
PUBLIC	PMC_From_I
PUBLIC	PMC_From_L
EXTRN	AllocateNumber:PROC
EXTRN	CommitNumber:PROC
EXTRN	number_zero:BYTE
;	COMDAT pdata
pdata	SEGMENT
$pdata$From_I_Imp DD imagerel $LN8
	DD	imagerel $LN8+93
	DD	imagerel $unwind$From_I_Imp
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$From_L_Imp DD imagerel $LN24
	DD	imagerel $LN24+96
	DD	imagerel $unwind$From_L_Imp
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_From_I DD imagerel $LN14
	DD	imagerel $LN14+123
	DD	imagerel $unwind$PMC_From_I
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$PMC_From_L DD imagerel $LN30
	DD	imagerel $LN30+126
	DD	imagerel $unwind$PMC_From_L
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_From_L DD 040a01H
	DD	07340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$PMC_From_I DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$From_L_Imp DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$From_I_Imp DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
;	COMDAT _LZCNT_ALT_UNIT
_TEXT	SEGMENT
x$ = 8
_LZCNT_ALT_UNIT PROC					; COMDAT

; 630  :         if (x == 0)

	test	rcx, rcx
	jne	SHORT $LN2@LZCNT_ALT_

; 631  :             return (sizeof(x) * 8);

	mov	eax, 64					; 00000040H

; 655  :     }

	ret	0
$LN2@LZCNT_ALT_:

; 632  : #ifdef _M_IX86
; 633  :         _UINT32_T pos;
; 634  : #ifdef _MSC_VER
; 635  :         _BitScanReverse(&pos, x);
; 636  : #elif defined(__GNUC__)
; 637  :         __asm__("bsrl %1, %0" : "=r"(pos) : "rm"(x));
; 638  : #else
; 639  : #error unknown compiler
; 640  : #endif
; 641  : #elif defined(_M_X64)
; 642  : #ifdef _MSC_VER
; 643  :         _UINT32_T pos;
; 644  :         _BitScanReverse64(&pos, x);

	bsr	rcx, rcx

; 645  : #elif defined(__GNUC__)
; 646  :         _UINT64_T pos;
; 647  :         __asm__("bsrq %1, %0" : "=r"(pos) : "rm"(x));
; 648  : #else
; 649  : #error unknown compiler
; 650  : #endif
; 651  : #else
; 652  : #error unknown platform
; 653  : #endif
; 654  :         return (sizeof(x) * 8 - 1 - pos);

	mov	eax, 63					; 0000003fH
	sub	eax, ecx

; 655  :     }

	ret	0
_LZCNT_ALT_UNIT ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
;	COMDAT _LZCNT_ALT_32
_TEXT	SEGMENT
x$ = 8
_LZCNT_ALT_32 PROC					; COMDAT

; 597  :         if (x == 0)

	test	ecx, ecx
	jne	SHORT $LN2@LZCNT_ALT_

; 598  :             return (sizeof(x) * 8);

	mov	eax, 32					; 00000020H

; 608  :     }

	ret	0
$LN2@LZCNT_ALT_:

; 599  :         _UINT32_T pos;
; 600  : #ifdef _MSC_VER
; 601  :         _BitScanReverse(&pos, x);

	bsr	ecx, ecx

; 602  : #elif defined(__GNUC__)
; 603  :         __asm__("bsrl %1, %0" : "=r"(pos) : "rm"(x));
; 604  : #else
; 605  : #error unknown compiler
; 606  : #endif
; 607  :         return (sizeof(x) * 8 - 1 - pos);

	mov	eax, 31
	sub	eax, ecx

; 608  :     }

	ret	0
_LZCNT_ALT_32 ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
;	COMDAT _FROMDWORDTOWORD
_TEXT	SEGMENT
value$ = 8
result_high$ = 16
_FROMDWORDTOWORD PROC					; COMDAT

; 183  :         *result_high = (_UINT32_T)(value >> 32);

	mov	rax, rcx
	shr	rax, 32					; 00000020H
	mov	DWORD PTR [rdx], eax

; 184  :         return ((_UINT32_T)value);

	mov	eax, ecx

; 185  :     }

	ret	0
_FROMDWORDTOWORD ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
;	COMDAT PMC_From_L
_TEXT	SEGMENT
p$ = 48
x$ = 48
o$ = 56
PMC_From_L PROC						; COMDAT

; 112  : {

$LN30:
	mov	QWORD PTR [rsp+16], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rdi, rdx
	mov	rbx, rcx

; 113  :     NUMBER_HEADER* p;
; 114  :     PMC_STATUS_CODE result;
; 115  :     if (sizeof(__UNIT_TYPE) * 2 < sizeof(x))
; 116  :     {
; 117  :         // 32bit–¢–ž‚ÌCPU‚É‚Í–¢‘Î‰ž
; 118  :         return (PMC_STATUS_INTERNAL_ERROR);
; 119  :     }
; 120  :     if (x == 0)

	test	rcx, rcx
	jne	SHORT $LN3@PMC_From_L

; 121  :         *o = &number_zero;

	lea	rax, OFFSET FLAT:number_zero
	mov	QWORD PTR [rdx], rax

; 127  :     }
; 128  : #ifdef _DEBUG
; 129  :     if ((result = CheckNumber(*o)) != PMC_STATUS_OK)
; 130  :         return (result);
; 131  : #endif
; 132  :     return (PMC_STATUS_OK);

	xor	eax, eax

; 133  : }

	mov	rbx, QWORD PTR [rsp+56]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
$LN3@PMC_From_L:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h

; 644  :         _BitScanReverse64(&pos, x);

	bsr	rax, rbx

; 654  :         return (sizeof(x) * 8 - 1 - pos);

	mov	ecx, 63					; 0000003fH
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c

; 81   :         __UNIT_TYPE x_bit_length = sizeof(x) * 8 - _LZCNT_ALT_UNIT((__UNIT_TYPE)x);

	mov	edx, 64					; 00000040H
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h

; 654  :         return (sizeof(x) * 8 - 1 - pos);

	sub	ecx, eax
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c

; 82   :         if ((result = AllocateNumber(o, x_bit_length, NULL)) != PMC_STATUS_OK)

	xor	r8d, r8d
	movsxd	rax, ecx
	lea	rcx, QWORD PTR p$[rsp]
	sub	rdx, rax
	call	AllocateNumber
	test	eax, eax
	jne	SHORT $LN7@PMC_From_L

; 83   :             return (result);
; 84   :         (*o)->BLOCK[0] = (__UNIT_TYPE)x;

	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax+56]
	mov	QWORD PTR [rcx], rbx

; 85   :     }
; 86   :     CommitNumber(*o);

	mov	rcx, QWORD PTR p$[rsp]
	call	CommitNumber

; 122  :     else
; 123  :     {
; 124  :         if ((result = From_L_Imp(x, &p)) != PMC_STATUS_OK)
; 125  :             return (result);
; 126  :         *o = p;

	mov	rax, QWORD PTR p$[rsp]
	mov	QWORD PTR [rdi], rax

; 127  :     }
; 128  : #ifdef _DEBUG
; 129  :     if ((result = CheckNumber(*o)) != PMC_STATUS_OK)
; 130  :         return (result);
; 131  : #endif
; 132  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN7@PMC_From_L:

; 133  : }

	mov	rbx, QWORD PTR [rsp+56]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
PMC_From_L ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
;	COMDAT PMC_From_I
_TEXT	SEGMENT
x$ = 48
o$ = 56
p$1 = 64
PMC_From_I PROC						; COMDAT

; 91   : {

$LN14:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	ebx, ecx
	mov	rdi, rdx

; 92   :     PMC_STATUS_CODE result;
; 93   :     if (sizeof(__UNIT_TYPE) < sizeof(x))
; 94   :         return (PMC_STATUS_INTERNAL_ERROR);
; 95   :     if (x == 0)

	test	ecx, ecx
	jne	SHORT $LN3@PMC_From_I

; 96   :         *o = &number_zero;

	lea	rax, OFFSET FLAT:number_zero
	mov	QWORD PTR [rdx], rax

; 103  :     }
; 104  : #ifdef _DEBUG
; 105  :     if ((result = CheckNumber(*o)) != PMC_STATUS_OK)
; 106  :         return (result);
; 107  : #endif
; 108  :     return (PMC_STATUS_OK);

	xor	eax, eax

; 109  : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
$LN3@PMC_From_I:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h

; 601  :         _BitScanReverse(&pos, x);

	bsr	eax, ebx

; 607  :         return (sizeof(x) * 8 - 1 - pos);

	mov	ecx, 31
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c

; 41   :     if ((result = AllocateNumber(o, sizeof(x) * 8 - _LZCNT_ALT_32(x), NULL)) != PMC_STATUS_OK)

	mov	edx, 32					; 00000020H
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h

; 607  :         return (sizeof(x) * 8 - 1 - pos);

	sub	ecx, eax
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c

; 41   :     if ((result = AllocateNumber(o, sizeof(x) * 8 - _LZCNT_ALT_32(x), NULL)) != PMC_STATUS_OK)

	xor	r8d, r8d
	movsxd	rax, ecx
	lea	rcx, QWORD PTR p$1[rsp]
	sub	rdx, rax
	call	AllocateNumber
	test	eax, eax
	jne	SHORT $LN7@PMC_From_I

; 42   :         return (result);
; 43   :     (*o)->BLOCK[0] = x;

	mov	rax, QWORD PTR p$1[rsp]
	mov	rcx, QWORD PTR [rax+56]
	mov	QWORD PTR [rcx], rbx

; 44   :     CommitNumber(*o);

	mov	rcx, QWORD PTR p$1[rsp]
	call	CommitNumber

; 97   :     else
; 98   :     {
; 99   :         NUMBER_HEADER* p;
; 100  :         if ((result = From_I_Imp(x, &p)) != PMC_STATUS_OK)
; 101  :             return (result);
; 102  :         *o = p;

	mov	rax, QWORD PTR p$1[rsp]
	mov	QWORD PTR [rdi], rax

; 103  :     }
; 104  : #ifdef _DEBUG
; 105  :     if ((result = CheckNumber(*o)) != PMC_STATUS_OK)
; 106  :         return (result);
; 107  : #endif
; 108  :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN7@PMC_From_I:

; 109  : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
PMC_From_I ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
;	COMDAT Initialize_From
_TEXT	SEGMENT
feature$ = 8
Initialize_From PROC					; COMDAT

; 137  :     return (PMC_STATUS_OK);

	xor	eax, eax

; 138  : }

	ret	0
Initialize_From ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
;	COMDAT From_L_Imp
_TEXT	SEGMENT
x$ = 48
o$ = 56
From_L_Imp PROC						; COMDAT

; 49   : {

$LN24:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rdi, rdx
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h

; 630  :         if (x == 0)

	mov	edx, 64					; 00000040H
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c

; 49   : {

	mov	rbx, rcx
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h

; 630  :         if (x == 0)

	test	rcx, rcx
	jne	SHORT $LN21@From_L_Imp

; 631  :             return (sizeof(x) * 8);

	mov	r8d, edx
	jmp	SHORT $LN20@From_L_Imp
$LN21@From_L_Imp:

; 632  : #ifdef _M_IX86
; 633  :         _UINT32_T pos;
; 634  : #ifdef _MSC_VER
; 635  :         _BitScanReverse(&pos, x);
; 636  : #elif defined(__GNUC__)
; 637  :         __asm__("bsrl %1, %0" : "=r"(pos) : "rm"(x));
; 638  : #else
; 639  : #error unknown compiler
; 640  : #endif
; 641  : #elif defined(_M_X64)
; 642  : #ifdef _MSC_VER
; 643  :         _UINT32_T pos;
; 644  :         _BitScanReverse64(&pos, x);

	bsr	rax, rbx

; 645  : #elif defined(__GNUC__)
; 646  :         _UINT64_T pos;
; 647  :         __asm__("bsrq %1, %0" : "=r"(pos) : "rm"(x));
; 648  : #else
; 649  : #error unknown compiler
; 650  : #endif
; 651  : #else
; 652  : #error unknown platform
; 653  : #endif
; 654  :         return (sizeof(x) * 8 - 1 - pos);

	mov	r8d, 63					; 0000003fH
	sub	r8d, eax
$LN20@From_L_Imp:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c

; 81   :         __UNIT_TYPE x_bit_length = sizeof(x) * 8 - _LZCNT_ALT_UNIT((__UNIT_TYPE)x);

	movsxd	rax, r8d

; 82   :         if ((result = AllocateNumber(o, x_bit_length, NULL)) != PMC_STATUS_OK)

	mov	rcx, rdi
	sub	rdx, rax
	xor	r8d, r8d
	call	AllocateNumber
	test	eax, eax
	jne	SHORT $LN1@From_L_Imp

; 83   :             return (result);
; 84   :         (*o)->BLOCK[0] = (__UNIT_TYPE)x;

	mov	rax, QWORD PTR [rdi]
	mov	rcx, QWORD PTR [rax+56]
	mov	QWORD PTR [rcx], rbx

; 85   :     }
; 86   :     CommitNumber(*o);

	mov	rcx, QWORD PTR [rdi]
	call	CommitNumber

; 87   :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@From_L_Imp:

; 88   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
From_L_Imp ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c
;	COMDAT From_I_Imp
_TEXT	SEGMENT
x$ = 48
o$ = 56
From_I_Imp PROC						; COMDAT

; 39   : {

$LN8:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	ebx, ecx
	mov	rdi, rdx
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_inline_func.h

; 597  :         if (x == 0)

	mov	edx, 32					; 00000020H
	test	ecx, ecx
	jne	SHORT $LN5@From_I_Imp

; 598  :             return (sizeof(x) * 8);

	mov	r8d, edx
	jmp	SHORT $LN4@From_I_Imp
$LN5@From_I_Imp:

; 599  :         _UINT32_T pos;
; 600  : #ifdef _MSC_VER
; 601  :         _BitScanReverse(&pos, x);

	bsr	eax, ebx

; 602  : #elif defined(__GNUC__)
; 603  :         __asm__("bsrl %1, %0" : "=r"(pos) : "rm"(x));
; 604  : #else
; 605  : #error unknown compiler
; 606  : #endif
; 607  :         return (sizeof(x) * 8 - 1 - pos);

	mov	r8d, 31
	sub	r8d, eax
$LN4@From_I_Imp:
; File z:\sources\lunor\repos\rougemeilland\palmtree.math.core.uint\palmtree.math.core.uint\pmc_from.c

; 41   :     if ((result = AllocateNumber(o, sizeof(x) * 8 - _LZCNT_ALT_32(x), NULL)) != PMC_STATUS_OK)

	movsxd	rax, r8d
	mov	rcx, rdi
	sub	rdx, rax
	xor	r8d, r8d
	call	AllocateNumber
	test	eax, eax
	jne	SHORT $LN1@From_I_Imp

; 42   :         return (result);
; 43   :     (*o)->BLOCK[0] = x;

	mov	rax, QWORD PTR [rdi]
	mov	rcx, QWORD PTR [rax+56]
	mov	QWORD PTR [rcx], rbx

; 44   :     CommitNumber(*o);

	mov	rcx, QWORD PTR [rdi]
	call	CommitNumber

; 45   :     return (PMC_STATUS_OK);

	xor	eax, eax
$LN1@From_I_Imp:

; 46   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
From_I_Imp ENDP
_TEXT	ENDS
END
